Repository cse110-fa22-group6/cse110-fa22-group6, pull requests merged in 2022-11, with the labels that each got.

#23 Created issue template for meeting minutes
  .github/ISSUE_TEMPLATE/meeting-minute.md
  .github/ISSUE_TEMPLATE/minutes_issue_template
Labels: todo, meeting minutes

#25 Added Meeting Minutes for the first Sprint
  admin/meetings/110222-sprint_1.md
Labels: todo, meeting minutes

#27 1st Meeting Minutes for Sprint 1 Front End
  admin/meetings/110322-sprint_1_front_end.md
Labels: todo, meeting minutes

#29 Create super-linter.yml
  .github/workflows/super-linter.yml
  README.md
Labels: enhancement, todo

#32 Moved 110122 MM and added new MMs
  admin/meetings/110122-weekly.md
  admin/meetings/110822-weekly.md
  admin/meetings/110922-sprint_1.md
Labels: meeting minutes

#42 Create 111322-browserLocalStorage-storage.md
  specs/ADR/111322-browserLocalStorage-storage.md
Labels: documentation

#65 Add Snake Case Check Into ESLint
  .eslintrc.yml
  package-lock.json
  package.json
Labels: enhancement

#58 Frontend Integration
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/meeting-minute.md
  .gitignore
  .vscode/settings.json
  110122-weekly.md
  README.md
  admin/branding/icon-transparent.png
  admin/branding/logo.ico
  admin/meetings/101122-weekly.md
  admin/meetings/101822-weekly.md
  admin/meetings/101922-brainstorm.md
  admin/meetings/102022-brainstorm.md
  admin/meetings/102122-brainstorm.md
  admin/meetings/102422-pitch_discussion.md
  admin/meetings/102622-pitch_discussion.md
  admin/meetings/110222-sprint_1.md
  admin/meetings/110322-sprint_1_front_end.md
  admin/misc/rules.md
  admin/video/link.md
  reference/jobCardTemplate.html
  source/.keep
  source/assets/font/demo.html
  source/assets/font/stylesheet.css
  source/assets/scripts/add_popup.js
  source/assets/scripts/delete_popup.js
  source/assets/scripts/edit_popup.js
  source/assets/scripts/job_card.js
  source/assets/scripts/progres_bar.js
  source/assets/styles/dialogues.css
  source/assets/styles/jobcard.css
  source/assets/styles/main.css
  source/index.html
  specs/brainstorm/Wireframes/README.md
Labels: help wanted, todo

#74 Pipeline jcyan jest
  .github/workflows/jest.yml
  .gitignore
  package-lock.json
  package.json
Labels: enhancement, pipeline

#77 Puppeteer Integrated
  .eslintrc.yml
  __tests__/sample.test.js
  package-lock.json
  package.json
Labels: enhancement, pipeline

#94 Darkmode feature implemented
  admin/branding/icon_darkmode.png
  source/assets/scripts/dark_mode.js
  source/assets/styles/dialogues.css
  source/assets/styles/jobcard.css
  source/assets/styles/main.css
  source/index.html
Labels: enhancement, frontend

#101 ESLint Hotfix
  .eslintrc.yml
  .github/workflows/eslint.yml
  package-lock.json
  package.json
Labels: pipeline, hotfix

#102 Merge Updated Pipeline
  .eslintrc.yml
  .github/workflows/eslint.yml
  package-lock.json
  package.json
Labels: pipeline

#96 Filter feature jcyan
  admin/branding/icon-transparent.png
  source/.keep
  source/assets/scripts/JobCard.js
  source/assets/scripts/initialDisplay.js
  source/assets/scripts/job_card.js
  source/assets/scripts/jobcardtle.js
  source/assets/styles/main.css
  source/index.html
Labels: enhancement

#109 Fixed JSDoc
  .github/workflows/jsdocs.yml
  package-lock.json
  package.json
  specs/documentation/JobCard.html
  specs/documentation/JobCard.js.html
  specs/documentation/index.html
Labels: bug, pipeline

#107 Fixed CSSLint
  .github/workflows/csslint.yml
  source/assets/scripts/JobCard.js
Labels: bug, pipeline

#114 Codacy Code Quality
  .github/workflows/codacy-analysis.yml
  README.md
  specs/documentation/JobCard.html
  specs/documentation/JobCard.js.html
  specs/documentation/index.html
Labels: enhancement, pipeline

#117 Fix ESLint Errors
  source/assets/scripts/JobCard.js
  source/assets/scripts/add_popup.js
  source/assets/scripts/delete_popup.js
  source/assets/scripts/initialDisplay.js
  source/assets/scripts/job_card.js
  source/assets/scripts/jobcardtle.js
  source/assets/scripts/progres_bar.js
  specs/documentation/JobCard.js.html
  specs/documentation/global.html
  specs/documentation/index.html
  specs/documentation/initialDisplay.js.html
  specs/documentation/job_card.js.html
  specs/documentation/jobcardtle.js.html
  specs/documentation/progres_bar.js.html
Labels: todo

#119 Prettier Fix
  .github/workflows/prettier.yml
  specs/documentation/JobCard.html
  specs/documentation/JobCard.js.html
  specs/documentation/global.html
  specs/documentation/index.html
  specs/documentation/initialDisplay.js.html
  specs/documentation/job_card.js.html
  specs/documentation/jobcardtle.js.html
  specs/documentation/progres_bar.js.html
Labels: enhancement, pipeline

#120 Snakecase for ESLint
  .eslintrc.yml
  package-lock.json
  source/assets/scripts/JobCard.js
  source/assets/scripts/initialDisplay.js
  source/assets/scripts/job_card.js
  source/assets/scripts/jobcardtle.js
  source/assets/scripts/progres_bar.js
  specs/documentation/JobCard.js.html
  specs/documentation/global.html
  specs/documentation/index.html
  specs/documentation/initialDisplay.js.html
  specs/documentation/job_card.js.html
  specs/documentation/jobcardtle.js.html
  specs/documentation/progres_bar.js.html
Labels: enhancement, pipeline

#123 Update Testing Branch with new Pipeline with Prettier Fix
  .eslintrc.yml
  .github/workflows/prettier.yml
  README.md
  package-lock.json
  source/assets/scripts/JobCard.js
  source/assets/scripts/initialDisplay.js
  source/assets/scripts/job_card.js
  source/assets/scripts/jobcardtle.js
  source/assets/scripts/progres_bar.js
  specs/documentation/JobCard.html
  specs/documentation/JobCard.js.html
  specs/documentation/global.html
  specs/documentation/index.html
  specs/documentation/initialDisplay.js.html
  specs/documentation/job_card.js.html
  specs/documentation/jobcardtle.js.html
  specs/documentation/progres_bar.js.html
Labels: pipeline
