Repository cse110-fa22-group6/cse110-fa22-group6, pull requests merged in 2022-12, with the labels that each got.

#126 Testing filepath hotfix jcyan
  source/assets/styles/jobcard.css
  source/index.html
  specs/documentation/JobCard.js.html
  specs/documentation/global.html
  specs/documentation/index.html
  specs/documentation/initialDisplay.js.html
  specs/documentation/job_card.js.html
  specs/documentation/jobcardtle.js.html
  specs/documentation/progres_bar.js.html
Labels: bug, hotfix

#122 Fixed CSS Linting Errors
  .stylelintrc.json
  __tests__/unit-tests.js
  package-lock.json
  package.json
  source/assets/scripts/JobCard.js
  source/assets/scripts/add_popup.js
  source/assets/scripts/delete_popup.js
  source/assets/scripts/edit_popup.js
  source/assets/scripts/initialDisplay.js
  source/assets/scripts/job_card.js
  source/assets/scripts/jobcardtle.js
  source/assets/scripts/progres_bar.js
  source/assets/styles/dialogues.css
  source/assets/styles/jobcard.css
  source/assets/styles/main.css
  source/index.html
  specs/documentation/JobCard.js.html
  specs/documentation/global.html
  specs/documentation/index.html
  specs/documentation/initialDisplay.js.html
  specs/documentation/job_card.js.html
  specs/documentation/jobcardtle.js.html
  specs/documentation/progres_bar.js.html
Labels: todo

#127 Fixed filepaths for Edit and Delete Icons
  __tests__/unit-tests.js
  source/assets/scripts/JobCard.js
  specs/documentation/JobCard.js.html
  specs/documentation/global.html
  specs/documentation/index.html
  specs/documentation/initialDisplay.js.html
  specs/documentation/job_card.js.html
  specs/documentation/jobcardtle.js.html
  specs/documentation/progres_bar.js.html
Labels: bug, hotfix

#128 Fix Broken Code due to auto lint fix
  .github/workflows/jest.yml
  __tests__/unit-tests.js
  source/assets/scripts/JobCard.js
  source/assets/scripts/add_popup.js
  source/assets/scripts/edit_popup.js
  source/assets/scripts/initialDisplay.js
  source/assets/scripts/job_card.js
  source/assets/scripts/jobcardtle.js
  source/assets/scripts/progres_bar.js
  specs/documentation/JobCard.js.html
  specs/documentation/global.html
  specs/documentation/index.html
  specs/documentation/initialDisplay.js.html
  specs/documentation/job_card.js.html
  specs/documentation/jobcardtle.js.html
  specs/documentation/progres_bar.js.html
Labels: bug

#124 Update Readme
  README.md
  specs/documentation/JobCard.js.html
  specs/documentation/global.html
  specs/documentation/index.html
  specs/documentation/initialDisplay.js.html
  specs/documentation/job_card.js.html
  specs/documentation/jobcardtle.js.html
  specs/documentation/progres_bar.js.html
Labels: documentation

#130 Fix E2E Tests Not Passing
  .github/workflows/jest.yml
  README.md
  __tests__/unit-tests.js
  jest-puppeteer.config.js
  specs/documentation/JobCard.js.html
  specs/documentation/global.html
  specs/documentation/index.html
  specs/documentation/initialDisplay.js.html
  specs/documentation/job_card.js.html
  specs/documentation/jobcardtle.js.html
  specs/documentation/progres_bar.js.html
Labels: bug, testing

#137 Andrei unit tests
  __tests__/unit-tests.js
  specs/documentation/JobCard.js.html
  specs/documentation/global.html
  specs/documentation/index.html
  specs/documentation/initialDisplay.js.html
  specs/documentation/job_card.js.html
  specs/documentation/jobcardtle.js.html
  specs/documentation/progres_bar.js.html
Labels: testing

#138 Meeting minutes, sprint 2 retro and review
  admin/meetings/112222-weekly.md
  admin/meetings/112322-sprint_2_checkIn.md
  admin/meetings/112822-sprint_2_checkIn.md
  admin/meetings/112922-weekly.md
  admin/meetings/113022-sprint_2_retrospective.md
  admin/meetings/113022-sprint_2_review.md
  source/assets/styles/dialogues.css
  specs/documentation/JobCard.js.html
  specs/documentation/global.html
  specs/documentation/index.html
  specs/documentation/initialDisplay.js.html
  specs/documentation/job_card.js.html
  specs/documentation/jobcardtle.js.html
  specs/documentation/progres_bar.js.html
Labels: documentation, admin, awaiting review

#140 Fix Jest Navigation Error and Set Timeout
  __tests__/unit-tests.js
  specs/documentation/JobCard.js.html
  specs/documentation/global.html
  specs/documentation/index.html
  specs/documentation/initialDisplay.js.html
  specs/documentation/job_card.js.html
  specs/documentation/jobcardtle.js.html
  specs/documentation/progres_bar.js.html
Labels: testing, awaiting review

#139 Update README
  README.md
  specs/documentation/JobCard.js.html
  specs/documentation/README.md
  specs/documentation/global.html
  specs/documentation/index.html
  specs/documentation/initialDisplay.js.html
  specs/documentation/job_card.js.html
  specs/documentation/jobcardtle.js.html
  specs/documentation/progres_bar.js.html
Labels: documentation, awaiting review

#110 Merge Backend into Integration
  source/assets/scripts/Job_card_shadowDOM.js
  source/assets/scripts/add_popup.js
  source/assets/scripts/delete_popup.js
  source/assets/scripts/edit_popup.js
  source/assets/scripts/initialDisplay.js
  source/assets/scripts/initial_display.js
  source/assets/scripts/job_card.js
  source/assets/scripts/jobcardtle.js
  source/assets/scripts/progres_bar.js
  source/assets/styles/dialogues.css
  source/assets/styles/main.css
  source/index.html
  specs/documentation/Job_card_shadowDOM.js.html
  specs/documentation/global.html
  specs/documentation/index.html
  specs/documentation/initial_display.js.html
Labels: help wanted, todo, backend, backlog

#147 Front back end integration testing place
  __tests__/unit-tests.js
  admin/branding/icon_darkmode.png
  admin/branding/logo.ico
  source/assets/scripts/Job_card_shadowDOM.js
  source/assets/scripts/add_popup.js
  source/assets/scripts/dark_mode.js
  source/assets/scripts/delete_popup.js
  source/assets/scripts/edit_popup.js
  source/assets/scripts/initialDisplay.js
  source/assets/scripts/initial_display.js
  source/assets/scripts/job_card.js
  source/assets/scripts/jobcardtle.js
  source/assets/scripts/progres_bar.js
  source/assets/styles/darkmode.css
  source/assets/styles/dialogues.css
  source/assets/styles/main.css
  source/index.html
  specs/documentation/Job_card_shadowDOM.js.html
  specs/documentation/global.html
  specs/documentation/index.html
  specs/documentation/initialDisplay.js.html
  specs/documentation/initial_display.js.html
Labels: awaiting review

#150 update jsdoc and prettier to not run on main
  .github/workflows/jsdocs.yml
  .github/workflows/prettier.yml
  source/assets/scripts/Job_card_shadowDOM.js
  source/assets/scripts/dark_mode.js
  source/assets/scripts/initial_display.js
  source/assets/styles/darkmode.css
  specs/documentation/Job_card_shadowDOM.js.html
  specs/documentation/global.html
  specs/documentation/index.html
  specs/documentation/initial_display.js.html
Labels: bug, pipeline

#149 Fix Frontend Errors - Bad Dialogue Layout
  source/assets/styles/dialogues.css
  specs/documentation/Job_card_shadowDOM.js.html
  specs/documentation/global.html
  specs/documentation/index.html
  specs/documentation/initial_display.js.html
Labels: bug, frontend
